# Generated by Django 2.2.5 on 2019-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORIO', '0002_auto_20190916_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='codigoCat',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='codigoDoc',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='codigoExa',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='codigoPac',
        ),
        migrations.AddField(
            model_name='examen',
            name='fechaExa',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
