# Generated by Django 2.2.5 on 2019-09-23 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORIO', '0003_auto_20190923_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fechaExa',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
