# Generated by Django 2.2.5 on 2019-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORIO', '0004_auto_20190923_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='fechaExa',
        ),
        migrations.AddField(
            model_name='examen',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
