# Generated by Django 2.2.5 on 2019-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORIO', '0006_remove_examen_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='detalleCat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='apellidoDoc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='apellidoDoc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='apellidoPac',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='categoriaExa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='fechaExa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='nombreDoc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='nombrePac',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='rutPac',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidoPac',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direccionDoc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rutDoc',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefonoDoc',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='descripcionExa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccionPac',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rutPac',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoPac',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
