# Generated by Django 2.2.5 on 2019-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORIO', '0007_auto_20191011_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fechaExa',
            field=models.DateField(null=True),
        ),
    ]
